name: "Post to Issue"
description: "Automatically post articles to GitHub issues"
branding:
  icon: table
  color: white
inputs:
  token:
    required: true
    description: A GitHub personal access token with write access to the project
  branch:
    description: "The branch where you place your articles."
    required: false
    default: "master"
  doc-dir:
    description: "The directory where your articles are at."
    required: false
    default: "docs"
  assets-prefix:
    description: "Assets folder, where you place your images (under the same folder of the article)."
    required: false
    default: "assets/"
runs:
  using: "node20"
  main: "dist/index.js"
